# Generated by Django 4.2.2 on 2023-07-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mistareas', '0002_alter_estados_options_alter_etiquetas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='etiquetas',
            name='etiqueta',
            field=models.CharField(max_length=20, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_modifica',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='id_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistareas.estados', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='id_etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistareas.etiquetas', verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='titulo',
            field=models.CharField(max_length=45, verbose_name='Titulo'),
        ),
    ]
