# Generated by Django 4.2.2 on 2023-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistareas', '0004_tareas_observaciones_alter_tareas_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=20, verbose_name='Etiqueta')),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'prioridades',
            },
        ),
    ]
